#!/usr/bin/env bash

set -euo pipefail
uptime="`uptime -p | sed -e 's/up //g'`"

declare -A actions=(
  [Shutdown]="systemctl poweroff"
  [Reboot]="systemctl reboot"
  [Suspend]="systemctl suspend"
  [Log Out]="hyprctl dispatch exit"
)

options=("Shutdown" "Reboot" "Suspend" "Log Out")

chosen=$(printf "%s\n" "${options[@]}" | rofi -dmenu \
                                              -mesg "Uptime: $uptime" \
                                              -theme-str 'configuration {show-icons: false;} window {width: 300px;} inputbar {enabled: false;} element-text {vertical-align: 0.50; horizontal-align: 0.50;} mode-switcher {enabled: false;}')

if [[ -n "$chosen" && "${actions[$chosen]+isset}" ]]; then
  ${actions[$chosen]}
fi
