#!/usr/bin/env bash
IFS=$'\n'

if [ "$@" ]
then
    desc="$*"
    device=$(pactl list sinks|grep -C2 -F "Description: $desc"|grep Name|cut -d: -f2|xargs)
    if pactl set-default-sink "$device"
    then
        notify-send "Activated: $desc"
    else
        notify-send "Error activating $desc"
    fi
else
    echo -en "\x00prompt\x1fSelect Output\n"
    for x in $(pactl list sinks | grep -A2 'Ports' | awk '{print $1}' | cut -d ':' -f1 | sort)
    do
        echo "$x"|xargs
    done
fi
